use anyhow::Result;
use colored::*;
use std::fs;
use std::path::Path;

use crate::cli::InitArgs;

pub async fn run(args: InitArgs) -> Result<()> {
    let project_name = &args.project_name;
    let root = Path::new(project_name);

    // Prevent accidental overwrite
    if root.exists() {
        anyhow::bail!("Directory '{}' already exists.", project_name);
    }

    // Create directories
    fs::create_dir_all(root.join("src"))?;

    // Cargo.toml
    let cargo_toml = format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
"#,
        name = project_name
    );

    // README.md
    let readme = format!(
        "# {}\n\nGenerated by PotKit.\n\nThis is a starter smart contract project.\n",
        project_name
    );

    // .gitignore
    let gitignore = "target/\nCargo.lock\n";

    // src/lib.rs
    let lib_rs = r#"pub struct Contract {
    value: bool,
}

impl Contract {
    pub fn new() -> Self {
        Self { value: false }
    }

    pub fn flip(&mut self) {
        self.value = !self.value;
    }

    pub fn get(&self) -> bool {
        self.value
    }
}
"#;

    // Write files
    fs::write(root.join("Cargo.toml"), cargo_toml)?;
    fs::write(root.join("README.md"), readme)?;
    fs::write(root.join(".gitignore"), gitignore)?;
    fs::write(root.join("src").join("lib.rs"), lib_rs)?;

    // Output
    println!(
        "{}",
        format!("✓ Project '{}' created successfully!", project_name)
            .bold()
            .green()
    );

    println!();
    println!("{}", "Generated files:".bold().cyan());
    println!("  Cargo.toml");
    println!("  README.md");
    println!("  .gitignore");
    println!("  src/lib.rs");

    println!();
    println!(
        "{}",
        "🚀 Your smart contract starter project is ready.".bold().green()
    );

    Ok(())
}